name: portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  go_router: ^14.2.7
  url_launcher: ^6.3.2
  flutter_svg: ^2.2.1
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.10.0
  flutter_physics: ^0.2.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/companies/
    - assets/images/works/
    - assets/images/works/fydez/
    - assets/images/works/loyalmate/
    - assets/images/works/moebel/
    - assets/images/works/remotederm/
    - assets/images/works/moebel/
    - assets/images/works/oraclium/
  fonts:
    - family: Zodiak
      fonts:
        - asset: assets/fonts/Zodiak-Variable.ttf
flutter_gen:
  output: lib/core/gen/ 
  line_length: 80 

  integrations:
    image: true
    flutter_svg: true